# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_32_30DMA_HPHPC/CAMC_24DMA_HPHPC.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_32_30DMA_HPHPC/CAMC_24DMA_HPHPC.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_32_30DMA_HPHPC/CAMC_24DMA_HPHPC.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_32_30DMA_HPHPC/CAMC_24DMA_HPHPC.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_32_30DMA_HPHPC/CAMC_24DMA_HPHPC.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_32_30DMA_HPHPC/CAMC_24DMA_HPHPC.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
