# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1/design_1_smartconnect_0_4.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "design_1_smartconnect_0_4_synth_1" START { ROLLUP_AUTO }
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu48dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.cache/wt [current_project]
set_property parent.project_path C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/elx22yz/Desktop/RFSoC/Vivado/HLS [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4.xci
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_1/bd_8bad_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_1/bd_8bad_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_2/bd_8bad_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_3/bd_8bad_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_4/bd_8bad_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_5/bd_8bad_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_6/bd_8bad_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_10/bd_8bad_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_11/bd_8bad_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_11/bd_8bad_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_12/bd_8bad_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_12/bd_8bad_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_13/bd_8bad_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_13/bd_8bad_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_14/bd_8bad_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_14/bd_8bad_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_15/bd_8bad_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_15/bd_8bad_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_16/bd_8bad_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_17/bd_8bad_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_17/bd_8bad_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_18/bd_8bad_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_18/bd_8bad_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_19/bd_8bad_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_19/bd_8bad_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_20/bd_8bad_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_20/bd_8bad_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_21/bd_8bad_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_21/bd_8bad_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_23/bd_8bad_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_24/bd_8bad_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_24/bd_8bad_m01arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_25/bd_8bad_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_25/bd_8bad_m01rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_26/bd_8bad_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_26/bd_8bad_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_27/bd_8bad_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_27/bd_8bad_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_28/bd_8bad_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_28/bd_8bad_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_30/bd_8bad_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_31/bd_8bad_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_31/bd_8bad_m02arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_32/bd_8bad_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_32/bd_8bad_m02rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_33/bd_8bad_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_33/bd_8bad_m02awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_34/bd_8bad_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_34/bd_8bad_m02wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_35/bd_8bad_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_35/bd_8bad_m02bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_37/bd_8bad_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_38/bd_8bad_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_38/bd_8bad_m03arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_39/bd_8bad_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_39/bd_8bad_m03rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_40/bd_8bad_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_40/bd_8bad_m03awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_41/bd_8bad_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_41/bd_8bad_m03wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_42/bd_8bad_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_42/bd_8bad_m03bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_44/bd_8bad_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_45/bd_8bad_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_45/bd_8bad_m04arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_46/bd_8bad_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_46/bd_8bad_m04rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_47/bd_8bad_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_47/bd_8bad_m04awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_48/bd_8bad_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_48/bd_8bad_m04wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_49/bd_8bad_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_49/bd_8bad_m04bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_51/bd_8bad_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_52/bd_8bad_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_52/bd_8bad_m05arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_53/bd_8bad_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_53/bd_8bad_m05rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_54/bd_8bad_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_54/bd_8bad_m05awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_55/bd_8bad_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_55/bd_8bad_m05wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_56/bd_8bad_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_56/bd_8bad_m05bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_58/bd_8bad_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_59/bd_8bad_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_59/bd_8bad_m06arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_60/bd_8bad_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_60/bd_8bad_m06rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_61/bd_8bad_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_61/bd_8bad_m06awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_62/bd_8bad_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_62/bd_8bad_m06wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_63/bd_8bad_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_63/bd_8bad_m06bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_65/bd_8bad_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_66/bd_8bad_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_66/bd_8bad_m07arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_67/bd_8bad_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_67/bd_8bad_m07rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_68/bd_8bad_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_68/bd_8bad_m07awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_69/bd_8bad_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_69/bd_8bad_m07wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_70/bd_8bad_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_70/bd_8bad_m07bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_72/bd_8bad_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_73/bd_8bad_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_73/bd_8bad_m08arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_74/bd_8bad_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_74/bd_8bad_m08rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_75/bd_8bad_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_75/bd_8bad_m08awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_76/bd_8bad_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_76/bd_8bad_m08wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_77/bd_8bad_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_77/bd_8bad_m08bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_79/bd_8bad_m09s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_80/bd_8bad_m09arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_80/bd_8bad_m09arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_81/bd_8bad_m09rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_81/bd_8bad_m09rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_82/bd_8bad_m09awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_82/bd_8bad_m09awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_83/bd_8bad_m09wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_83/bd_8bad_m09wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_84/bd_8bad_m09bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_84/bd_8bad_m09bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_86/bd_8bad_m10s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_87/bd_8bad_m10arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_87/bd_8bad_m10arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_88/bd_8bad_m10rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_88/bd_8bad_m10rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_89/bd_8bad_m10awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_89/bd_8bad_m10awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_90/bd_8bad_m10wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_90/bd_8bad_m10wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_91/bd_8bad_m10bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_91/bd_8bad_m10bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_93/bd_8bad_m11s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_94/bd_8bad_m11arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_94/bd_8bad_m11arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_95/bd_8bad_m11rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_95/bd_8bad_m11rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_96/bd_8bad_m11awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_96/bd_8bad_m11awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_97/bd_8bad_m11wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_97/bd_8bad_m11wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_98/bd_8bad_m11bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_98/bd_8bad_m11bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_100/bd_8bad_m12s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_101/bd_8bad_m12arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_101/bd_8bad_m12arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_102/bd_8bad_m12rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_102/bd_8bad_m12rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_103/bd_8bad_m12awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_103/bd_8bad_m12awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_104/bd_8bad_m12wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_104/bd_8bad_m12wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_105/bd_8bad_m12bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_105/bd_8bad_m12bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_107/bd_8bad_m13s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_108/bd_8bad_m13arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_108/bd_8bad_m13arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_109/bd_8bad_m13rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_109/bd_8bad_m13rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_110/bd_8bad_m13awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_110/bd_8bad_m13awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_111/bd_8bad_m13wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_111/bd_8bad_m13wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_112/bd_8bad_m13bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_112/bd_8bad_m13bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_114/bd_8bad_m14s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_115/bd_8bad_m14arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_115/bd_8bad_m14arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_116/bd_8bad_m14rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_116/bd_8bad_m14rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_117/bd_8bad_m14awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_117/bd_8bad_m14awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_118/bd_8bad_m14wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_118/bd_8bad_m14wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_119/bd_8bad_m14bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_119/bd_8bad_m14bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_121/bd_8bad_m15s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_122/bd_8bad_m15arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_122/bd_8bad_m15arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_123/bd_8bad_m15rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_123/bd_8bad_m15rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_124/bd_8bad_m15awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_124/bd_8bad_m15awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_125/bd_8bad_m15wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_125/bd_8bad_m15wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_126/bd_8bad_m15bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/bd_0/ip/ip_126/bd_8bad_m15bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/smartconnect.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1 -new_name design_1_smartconnect_0_4 -ip [get_ips design_1_smartconnect_0_4]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_smartconnect_0_4 -part xczu48dr-ffvg1517-2-e -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix design_1_smartconnect_0_4_ design_1_smartconnect_0_4.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_0_4_stub.v
 lappend ipCachedFiles design_1_smartconnect_0_4_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_0_4_stub.vhdl
 lappend ipCachedFiles design_1_smartconnect_0_4_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_0_4_sim_netlist.v
 lappend ipCachedFiles design_1_smartconnect_0_4_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_smartconnect_0_4_sim_netlist.vhdl
 lappend ipCachedFiles design_1_smartconnect_0_4_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp design_1_smartconnect_0_4.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips design_1_smartconnect_0_4]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all design_1_smartconnect_0_4_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_smartconnect_0_4.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file design_1_smartconnect_0_4_utilization_synth.rpt -pb design_1_smartconnect_0_4_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1/design_1_smartconnect_0_4.dcp c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1/design_1_smartconnect_0_4.dcp c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1/design_1_smartconnect_0_4_stub.v c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1/design_1_smartconnect_0_4_stub.vhdl c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1/design_1_smartconnect_0_4_sim_netlist.v c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.runs/design_1_smartconnect_0_4_synth_1/design_1_smartconnect_0_4_sim_netlist.vhdl c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

close [open .end.used_ip_cache.rst w]
}; # end if cacheID 

if {[file isdir C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.ip_user_files/ip/design_1_smartconnect_0_4]} {
  catch { 
    file copy -force c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_stub.v C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.ip_user_files/ip/design_1_smartconnect_0_4
  }
}

if {[file isdir C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.ip_user_files/ip/design_1_smartconnect_0_4]} {
  catch { 
    file copy -force c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4_stub.vhdl C:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.ip_user_files/ip/design_1_smartconnect_0_4
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "design_1_smartconnect_0_4_synth_1" END { }
