# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/design_1_smartconnect_0_3.xci
# IP: The module: 'design_1_smartconnect_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/bd_49ec.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_0/bd_49ec_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/bd_49ec_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/bd_49ec_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/bd_49ec_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/bd_49ec_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/bd_49ec_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_7/bd_49ec_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_8/bd_49ec_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_9/bd_49ec_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/bd_49ec_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_16/bd_49ec_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/bd_49ec_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/bd_49ec_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_22/bd_49ec_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/bd_49ec_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_29/bd_49ec_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/bd_49ec_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/bd_49ec_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_36/bd_49ec_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/bd_49ec_arsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/bd_49ec_rsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/bd_49ec_awsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/bd_49ec_wsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/bd_49ec_bsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/bd_49ec_s00a2s_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_16/bd_49ec_m00s2a_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/bd_49ec_m00arn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/bd_49ec_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/bd_49ec_m00rn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/bd_49ec_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_m00awn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_m00wn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_m00bn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/bd_49ec_m01s2a_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_m01arn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m01rn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m01awn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m01wn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m01bn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/bd_49ec_m02s2a_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/bd_49ec_m02arn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/bd_49ec_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m02rn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m02awn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m02wn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m02bn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/design_1_smartconnect_0_3.xci
# IP: The module: 'design_1_smartconnect_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/bd_49ec.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_0/bd_49ec_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/bd_49ec_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/bd_49ec_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/bd_49ec_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/bd_49ec_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/bd_49ec_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_7/bd_49ec_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_8/bd_49ec_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_9/bd_49ec_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/bd_49ec_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_16/bd_49ec_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/bd_49ec_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/bd_49ec_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_22/bd_49ec_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/bd_49ec_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_29/bd_49ec_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/bd_49ec_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/bd_49ec_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_36/bd_49ec_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/bd_49ec_arsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/bd_49ec_rsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/bd_49ec_awsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/bd_49ec_wsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/bd_49ec_bsw_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/bd_49ec_s00a2s_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_16/bd_49ec_m00s2a_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/bd_49ec_m00arn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/bd_49ec_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/bd_49ec_m00rn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/bd_49ec_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_m00awn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_m00wn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_m00bn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/bd_49ec_m01s2a_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_m01arn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m01rn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m01awn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m01wn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m01bn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/bd_49ec_m02s2a_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/bd_49ec_m02arn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/bd_49ec_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m02rn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m02awn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m02wn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m02bn_0_ooc.xdc

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
