# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_32/design_1_CAMC_0_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_32 || ORIG_REF_NAME==design_1_CAMC_0_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_32/design_1_axi_bram_ctrl_0_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_32 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_33/design_1_axi_dma_0_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_33 || ORIG_REF_NAME==design_1_axi_dma_0_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_31/design_1_axi_dma_1_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_31 || ORIG_REF_NAME==design_1_axi_dma_1_31} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_32/design_1_blk_mem_gen_0_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_32 || ORIG_REF_NAME==design_1_blk_mem_gen_0_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_33/design_1_CAMC_0_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_33 || ORIG_REF_NAME==design_1_CAMC_0_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_33/design_1_axi_bram_ctrl_0_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_33 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_34/design_1_axi_dma_0_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_34 || ORIG_REF_NAME==design_1_axi_dma_0_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_32/design_1_axi_dma_1_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_32 || ORIG_REF_NAME==design_1_axi_dma_1_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_33/design_1_blk_mem_gen_0_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_33 || ORIG_REF_NAME==design_1_blk_mem_gen_0_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_34/design_1_CAMC_0_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_34 || ORIG_REF_NAME==design_1_CAMC_0_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_34/design_1_axi_bram_ctrl_0_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_34 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_35/design_1_axi_dma_0_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_35 || ORIG_REF_NAME==design_1_axi_dma_0_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_33/design_1_axi_dma_1_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_33 || ORIG_REF_NAME==design_1_axi_dma_1_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_34/design_1_blk_mem_gen_0_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_34 || ORIG_REF_NAME==design_1_blk_mem_gen_0_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_35/design_1_CAMC_0_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_35 || ORIG_REF_NAME==design_1_CAMC_0_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_35/design_1_axi_bram_ctrl_0_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_35 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_36/design_1_axi_dma_0_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_36 || ORIG_REF_NAME==design_1_axi_dma_0_36} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_34/design_1_axi_dma_1_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_34 || ORIG_REF_NAME==design_1_axi_dma_1_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_35/design_1_blk_mem_gen_0_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_35 || ORIG_REF_NAME==design_1_blk_mem_gen_0_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_8/design_1_xbar_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_8 || ORIG_REF_NAME==design_1_xbar_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_4 || ORIG_REF_NAME==design_1_auto_us_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_5 || ORIG_REF_NAME==design_1_auto_us_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_6 || ORIG_REF_NAME==design_1_auto_us_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_7 || ORIG_REF_NAME==design_1_auto_us_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_8/design_1_auto_us_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_8 || ORIG_REF_NAME==design_1_auto_us_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_9/design_1_auto_us_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_9 || ORIG_REF_NAME==design_1_auto_us_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_10/design_1_auto_us_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_10 || ORIG_REF_NAME==design_1_auto_us_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_11/design_1_auto_us_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_11 || ORIG_REF_NAME==design_1_auto_us_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_12/design_1_auto_us_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_12 || ORIG_REF_NAME==design_1_auto_us_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_13/design_1_auto_us_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_13 || ORIG_REF_NAME==design_1_auto_us_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_14/design_1_auto_us_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_14 || ORIG_REF_NAME==design_1_auto_us_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_15/design_1_auto_us_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_15 || ORIG_REF_NAME==design_1_auto_us_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_8/design_1_axi_interconnect_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_8 || ORIG_REF_NAME==design_1_axi_interconnect_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_1 || ORIG_REF_NAME==design_1_smartconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_36/design_1_CAMC_0_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_36 || ORIG_REF_NAME==design_1_CAMC_0_36} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_36/design_1_axi_bram_ctrl_0_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_36 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_36} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_37/design_1_axi_dma_0_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_37 || ORIG_REF_NAME==design_1_axi_dma_0_37} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_35/design_1_axi_dma_1_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_35 || ORIG_REF_NAME==design_1_axi_dma_1_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_36/design_1_blk_mem_gen_0_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_36 || ORIG_REF_NAME==design_1_blk_mem_gen_0_36} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_37/design_1_CAMC_0_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_37 || ORIG_REF_NAME==design_1_CAMC_0_37} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_37/design_1_axi_bram_ctrl_0_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_37 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_37} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_38/design_1_axi_dma_0_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_38 || ORIG_REF_NAME==design_1_axi_dma_0_38} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_36/design_1_axi_dma_1_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_36 || ORIG_REF_NAME==design_1_axi_dma_1_36} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_37/design_1_blk_mem_gen_0_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_37 || ORIG_REF_NAME==design_1_blk_mem_gen_0_37} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_38/design_1_CAMC_0_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_38 || ORIG_REF_NAME==design_1_CAMC_0_38} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_38/design_1_axi_bram_ctrl_0_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_38 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_38} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_39/design_1_axi_dma_0_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_39 || ORIG_REF_NAME==design_1_axi_dma_0_39} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_37/design_1_axi_dma_1_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_37 || ORIG_REF_NAME==design_1_axi_dma_1_37} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_38/design_1_blk_mem_gen_0_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_38 || ORIG_REF_NAME==design_1_blk_mem_gen_0_38} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_39/design_1_CAMC_0_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_39 || ORIG_REF_NAME==design_1_CAMC_0_39} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_39/design_1_axi_bram_ctrl_0_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_39 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_39} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_40/design_1_axi_dma_0_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_40 || ORIG_REF_NAME==design_1_axi_dma_0_40} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_38/design_1_axi_dma_1_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_38 || ORIG_REF_NAME==design_1_axi_dma_1_38} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_39/design_1_blk_mem_gen_0_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_39 || ORIG_REF_NAME==design_1_blk_mem_gen_0_39} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_9/design_1_xbar_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_9 || ORIG_REF_NAME==design_1_xbar_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_16/design_1_auto_us_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_16 || ORIG_REF_NAME==design_1_auto_us_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_17/design_1_auto_us_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_17 || ORIG_REF_NAME==design_1_auto_us_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_18/design_1_auto_us_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_18 || ORIG_REF_NAME==design_1_auto_us_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_19/design_1_auto_us_19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_19 || ORIG_REF_NAME==design_1_auto_us_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_20/design_1_auto_us_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_20 || ORIG_REF_NAME==design_1_auto_us_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_21/design_1_auto_us_21.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_21 || ORIG_REF_NAME==design_1_auto_us_21} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_22/design_1_auto_us_22.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_22 || ORIG_REF_NAME==design_1_auto_us_22} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_23/design_1_auto_us_23.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_23 || ORIG_REF_NAME==design_1_auto_us_23} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_24/design_1_auto_us_24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_24 || ORIG_REF_NAME==design_1_auto_us_24} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_25/design_1_auto_us_25.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_25 || ORIG_REF_NAME==design_1_auto_us_25} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_26/design_1_auto_us_26.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_26 || ORIG_REF_NAME==design_1_auto_us_26} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_27/design_1_auto_us_27.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_27 || ORIG_REF_NAME==design_1_auto_us_27} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_28/design_1_auto_us_28.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_28 || ORIG_REF_NAME==design_1_auto_us_28} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_29/design_1_auto_us_29.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_29 || ORIG_REF_NAME==design_1_auto_us_29} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_30/design_1_auto_us_30.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_30 || ORIG_REF_NAME==design_1_auto_us_30} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_31/design_1_auto_us_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_31 || ORIG_REF_NAME==design_1_auto_us_31} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_9/design_1_axi_interconnect_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_9 || ORIG_REF_NAME==design_1_axi_interconnect_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_2/design_1_smartconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_2 || ORIG_REF_NAME==design_1_smartconnect_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_40/design_1_CAMC_0_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_40 || ORIG_REF_NAME==design_1_CAMC_0_40} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_40/design_1_axi_bram_ctrl_0_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_40 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_40} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_41/design_1_axi_dma_0_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_41 || ORIG_REF_NAME==design_1_axi_dma_0_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_39/design_1_axi_dma_1_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_39 || ORIG_REF_NAME==design_1_axi_dma_1_39} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_40/design_1_blk_mem_gen_0_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_40 || ORIG_REF_NAME==design_1_blk_mem_gen_0_40} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_41/design_1_CAMC_0_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_41 || ORIG_REF_NAME==design_1_CAMC_0_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_41/design_1_axi_bram_ctrl_0_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_41 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_42/design_1_axi_dma_0_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_42 || ORIG_REF_NAME==design_1_axi_dma_0_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_40/design_1_axi_dma_1_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_40 || ORIG_REF_NAME==design_1_axi_dma_1_40} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_41/design_1_blk_mem_gen_0_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_41 || ORIG_REF_NAME==design_1_blk_mem_gen_0_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_42/design_1_CAMC_0_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_42 || ORIG_REF_NAME==design_1_CAMC_0_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_42/design_1_axi_bram_ctrl_0_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_42 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_43/design_1_axi_dma_0_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_43 || ORIG_REF_NAME==design_1_axi_dma_0_43} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_41/design_1_axi_dma_1_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_41 || ORIG_REF_NAME==design_1_axi_dma_1_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_42/design_1_blk_mem_gen_0_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_42 || ORIG_REF_NAME==design_1_blk_mem_gen_0_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_43/design_1_CAMC_0_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_43 || ORIG_REF_NAME==design_1_CAMC_0_43} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_43/design_1_axi_bram_ctrl_0_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_43 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_43} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_44/design_1_axi_dma_0_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_44 || ORIG_REF_NAME==design_1_axi_dma_0_44} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_42/design_1_axi_dma_1_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_42 || ORIG_REF_NAME==design_1_axi_dma_1_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_43/design_1_blk_mem_gen_0_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_43 || ORIG_REF_NAME==design_1_blk_mem_gen_0_43} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_10/design_1_xbar_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_10 || ORIG_REF_NAME==design_1_xbar_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_32/design_1_auto_us_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_32 || ORIG_REF_NAME==design_1_auto_us_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_33/design_1_auto_us_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_33 || ORIG_REF_NAME==design_1_auto_us_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_34/design_1_auto_us_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_34 || ORIG_REF_NAME==design_1_auto_us_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_35/design_1_auto_us_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_35 || ORIG_REF_NAME==design_1_auto_us_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_36/design_1_auto_us_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_36 || ORIG_REF_NAME==design_1_auto_us_36} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_37/design_1_auto_us_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_37 || ORIG_REF_NAME==design_1_auto_us_37} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_38/design_1_auto_us_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_38 || ORIG_REF_NAME==design_1_auto_us_38} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_39/design_1_auto_us_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_39 || ORIG_REF_NAME==design_1_auto_us_39} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_40/design_1_auto_us_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_40 || ORIG_REF_NAME==design_1_auto_us_40} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_41/design_1_auto_us_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_41 || ORIG_REF_NAME==design_1_auto_us_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_42/design_1_auto_us_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_42 || ORIG_REF_NAME==design_1_auto_us_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_43/design_1_auto_us_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_43 || ORIG_REF_NAME==design_1_auto_us_43} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_44/design_1_auto_us_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_44 || ORIG_REF_NAME==design_1_auto_us_44} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_45/design_1_auto_us_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_45 || ORIG_REF_NAME==design_1_auto_us_45} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_46/design_1_auto_us_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_46 || ORIG_REF_NAME==design_1_auto_us_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_47/design_1_auto_us_47.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_47 || ORIG_REF_NAME==design_1_auto_us_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_10/design_1_axi_interconnect_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_10 || ORIG_REF_NAME==design_1_axi_interconnect_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_3/design_1_smartconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_3 || ORIG_REF_NAME==design_1_smartconnect_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_4/design_1_smartconnect_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_4 || ORIG_REF_NAME==design_1_smartconnect_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_44/design_1_CAMC_0_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_44 || ORIG_REF_NAME==design_1_CAMC_0_44} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_44/design_1_axi_bram_ctrl_0_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_44 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_44} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_45/design_1_axi_dma_0_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_45 || ORIG_REF_NAME==design_1_axi_dma_0_45} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_43/design_1_axi_dma_1_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_43 || ORIG_REF_NAME==design_1_axi_dma_1_43} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_44/design_1_blk_mem_gen_0_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_44 || ORIG_REF_NAME==design_1_blk_mem_gen_0_44} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_45/design_1_CAMC_0_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_45 || ORIG_REF_NAME==design_1_CAMC_0_45} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_45/design_1_axi_bram_ctrl_0_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_45 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_45} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_46/design_1_axi_dma_0_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_46 || ORIG_REF_NAME==design_1_axi_dma_0_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_44/design_1_axi_dma_1_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_44 || ORIG_REF_NAME==design_1_axi_dma_1_44} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_45/design_1_blk_mem_gen_0_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_45 || ORIG_REF_NAME==design_1_blk_mem_gen_0_45} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_46/design_1_CAMC_0_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_46 || ORIG_REF_NAME==design_1_CAMC_0_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_46/design_1_axi_bram_ctrl_0_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_46 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_47/design_1_axi_dma_0_47.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_47 || ORIG_REF_NAME==design_1_axi_dma_0_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_45/design_1_axi_dma_1_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_45 || ORIG_REF_NAME==design_1_axi_dma_1_45} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_46/design_1_blk_mem_gen_0_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_46 || ORIG_REF_NAME==design_1_blk_mem_gen_0_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_47/design_1_CAMC_0_47.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_47 || ORIG_REF_NAME==design_1_CAMC_0_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_47/design_1_axi_bram_ctrl_0_47.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_47 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_48/design_1_axi_dma_0_48.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_48 || ORIG_REF_NAME==design_1_axi_dma_0_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_46/design_1_axi_dma_1_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_46 || ORIG_REF_NAME==design_1_axi_dma_1_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_47/design_1_blk_mem_gen_0_47.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_47 || ORIG_REF_NAME==design_1_blk_mem_gen_0_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_11/design_1_xbar_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_11 || ORIG_REF_NAME==design_1_xbar_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_48/design_1_auto_us_48.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_48 || ORIG_REF_NAME==design_1_auto_us_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_49/design_1_auto_us_49.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_49 || ORIG_REF_NAME==design_1_auto_us_49} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_50/design_1_auto_us_50.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_50 || ORIG_REF_NAME==design_1_auto_us_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_51/design_1_auto_us_51.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_51 || ORIG_REF_NAME==design_1_auto_us_51} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_52/design_1_auto_us_52.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_52 || ORIG_REF_NAME==design_1_auto_us_52} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_53/design_1_auto_us_53.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_53 || ORIG_REF_NAME==design_1_auto_us_53} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_54/design_1_auto_us_54.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_54 || ORIG_REF_NAME==design_1_auto_us_54} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_55/design_1_auto_us_55.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_55 || ORIG_REF_NAME==design_1_auto_us_55} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_56/design_1_auto_us_56.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_56 || ORIG_REF_NAME==design_1_auto_us_56} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_57/design_1_auto_us_57.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_57 || ORIG_REF_NAME==design_1_auto_us_57} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_58/design_1_auto_us_58.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_58 || ORIG_REF_NAME==design_1_auto_us_58} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_59/design_1_auto_us_59.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_59 || ORIG_REF_NAME==design_1_auto_us_59} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_60/design_1_auto_us_60.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_60 || ORIG_REF_NAME==design_1_auto_us_60} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_61/design_1_auto_us_61.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_61 || ORIG_REF_NAME==design_1_auto_us_61} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_62/design_1_auto_us_62.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_62 || ORIG_REF_NAME==design_1_auto_us_62} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_63/design_1_auto_us_63.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_63 || ORIG_REF_NAME==design_1_auto_us_63} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_11/design_1_axi_interconnect_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_11 || ORIG_REF_NAME==design_1_axi_interconnect_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_5/design_1_smartconnect_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_5 || ORIG_REF_NAME==design_1_smartconnect_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_48/design_1_CAMC_0_48.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_48 || ORIG_REF_NAME==design_1_CAMC_0_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_48/design_1_axi_bram_ctrl_0_48.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_48 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_49/design_1_axi_dma_0_49.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_49 || ORIG_REF_NAME==design_1_axi_dma_0_49} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_47/design_1_axi_dma_1_47.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_47 || ORIG_REF_NAME==design_1_axi_dma_1_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_48/design_1_blk_mem_gen_0_48.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_48 || ORIG_REF_NAME==design_1_blk_mem_gen_0_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_49/design_1_CAMC_0_49.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_49 || ORIG_REF_NAME==design_1_CAMC_0_49} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_49/design_1_axi_bram_ctrl_0_49.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_49 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_49} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_50/design_1_axi_dma_0_50.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_50 || ORIG_REF_NAME==design_1_axi_dma_0_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_48/design_1_axi_dma_1_48.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_48 || ORIG_REF_NAME==design_1_axi_dma_1_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_49/design_1_blk_mem_gen_0_49.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_49 || ORIG_REF_NAME==design_1_blk_mem_gen_0_49} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_50/design_1_CAMC_0_50.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_50 || ORIG_REF_NAME==design_1_CAMC_0_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_50/design_1_axi_bram_ctrl_0_50.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_50 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_51/design_1_axi_dma_0_51.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_51 || ORIG_REF_NAME==design_1_axi_dma_0_51} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_49/design_1_axi_dma_1_49.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_49 || ORIG_REF_NAME==design_1_axi_dma_1_49} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_50/design_1_blk_mem_gen_0_50.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_50 || ORIG_REF_NAME==design_1_blk_mem_gen_0_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_51/design_1_CAMC_0_51.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_51 || ORIG_REF_NAME==design_1_CAMC_0_51} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_51/design_1_axi_bram_ctrl_0_51.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_51 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_51} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_52/design_1_axi_dma_0_52.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_52 || ORIG_REF_NAME==design_1_axi_dma_0_52} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_50/design_1_axi_dma_1_50.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_50 || ORIG_REF_NAME==design_1_axi_dma_1_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_51/design_1_blk_mem_gen_0_51.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_51 || ORIG_REF_NAME==design_1_blk_mem_gen_0_51} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_12/design_1_xbar_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_12 || ORIG_REF_NAME==design_1_xbar_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_64/design_1_auto_us_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_64 || ORIG_REF_NAME==design_1_auto_us_64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_65/design_1_auto_us_65.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_65 || ORIG_REF_NAME==design_1_auto_us_65} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_66/design_1_auto_us_66.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_66 || ORIG_REF_NAME==design_1_auto_us_66} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_67/design_1_auto_us_67.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_67 || ORIG_REF_NAME==design_1_auto_us_67} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_68/design_1_auto_us_68.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_68 || ORIG_REF_NAME==design_1_auto_us_68} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_69/design_1_auto_us_69.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_69 || ORIG_REF_NAME==design_1_auto_us_69} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_70/design_1_auto_us_70.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_70 || ORIG_REF_NAME==design_1_auto_us_70} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_71/design_1_auto_us_71.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_71 || ORIG_REF_NAME==design_1_auto_us_71} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_72/design_1_auto_us_72.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_72 || ORIG_REF_NAME==design_1_auto_us_72} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_73/design_1_auto_us_73.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_73 || ORIG_REF_NAME==design_1_auto_us_73} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_74/design_1_auto_us_74.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_74 || ORIG_REF_NAME==design_1_auto_us_74} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_75/design_1_auto_us_75.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_75 || ORIG_REF_NAME==design_1_auto_us_75} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_76/design_1_auto_us_76.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_76 || ORIG_REF_NAME==design_1_auto_us_76} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_77/design_1_auto_us_77.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_77 || ORIG_REF_NAME==design_1_auto_us_77} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_78/design_1_auto_us_78.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_78 || ORIG_REF_NAME==design_1_auto_us_78} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_79/design_1_auto_us_79.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_79 || ORIG_REF_NAME==design_1_auto_us_79} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_12/design_1_axi_interconnect_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_12 || ORIG_REF_NAME==design_1_axi_interconnect_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_7/design_1_smartconnect_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_7 || ORIG_REF_NAME==design_1_smartconnect_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_8/design_1_smartconnect_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_8 || ORIG_REF_NAME==design_1_smartconnect_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_56/design_1_CAMC_0_56.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_56 || ORIG_REF_NAME==design_1_CAMC_0_56} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_56/design_1_axi_bram_ctrl_0_56.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_56 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_56} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_57/design_1_axi_dma_0_57.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_57 || ORIG_REF_NAME==design_1_axi_dma_0_57} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_55/design_1_axi_dma_1_55.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_55 || ORIG_REF_NAME==design_1_axi_dma_1_55} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_56/design_1_blk_mem_gen_0_56.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_56 || ORIG_REF_NAME==design_1_blk_mem_gen_0_56} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_57/design_1_CAMC_0_57.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_57 || ORIG_REF_NAME==design_1_CAMC_0_57} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_57/design_1_axi_bram_ctrl_0_57.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_57 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_57} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_58/design_1_axi_dma_0_58.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_58 || ORIG_REF_NAME==design_1_axi_dma_0_58} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_56/design_1_axi_dma_1_56.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_56 || ORIG_REF_NAME==design_1_axi_dma_1_56} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_57/design_1_blk_mem_gen_0_57.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_57 || ORIG_REF_NAME==design_1_blk_mem_gen_0_57} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_58/design_1_CAMC_0_58.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_58 || ORIG_REF_NAME==design_1_CAMC_0_58} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_58/design_1_axi_bram_ctrl_0_58.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_58 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_58} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_59/design_1_axi_dma_0_59.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_59 || ORIG_REF_NAME==design_1_axi_dma_0_59} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_57/design_1_axi_dma_1_57.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_57 || ORIG_REF_NAME==design_1_axi_dma_1_57} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_58/design_1_blk_mem_gen_0_58.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_58 || ORIG_REF_NAME==design_1_blk_mem_gen_0_58} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_59/design_1_CAMC_0_59.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_59 || ORIG_REF_NAME==design_1_CAMC_0_59} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_59/design_1_axi_bram_ctrl_0_59.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_59 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_59} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_60/design_1_axi_dma_0_60.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_60 || ORIG_REF_NAME==design_1_axi_dma_0_60} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_58/design_1_axi_dma_1_58.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_58 || ORIG_REF_NAME==design_1_axi_dma_1_58} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_59/design_1_blk_mem_gen_0_59.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_59 || ORIG_REF_NAME==design_1_blk_mem_gen_0_59} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_14/design_1_xbar_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_14 || ORIG_REF_NAME==design_1_xbar_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_80/design_1_auto_us_80.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_80 || ORIG_REF_NAME==design_1_auto_us_80} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_81/design_1_auto_us_81.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_81 || ORIG_REF_NAME==design_1_auto_us_81} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_82/design_1_auto_us_82.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_82 || ORIG_REF_NAME==design_1_auto_us_82} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_83/design_1_auto_us_83.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_83 || ORIG_REF_NAME==design_1_auto_us_83} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_84/design_1_auto_us_84.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_84 || ORIG_REF_NAME==design_1_auto_us_84} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_85/design_1_auto_us_85.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_85 || ORIG_REF_NAME==design_1_auto_us_85} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_86/design_1_auto_us_86.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_86 || ORIG_REF_NAME==design_1_auto_us_86} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_87/design_1_auto_us_87.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_87 || ORIG_REF_NAME==design_1_auto_us_87} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_88/design_1_auto_us_88.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_88 || ORIG_REF_NAME==design_1_auto_us_88} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_89/design_1_auto_us_89.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_89 || ORIG_REF_NAME==design_1_auto_us_89} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_90/design_1_auto_us_90.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_90 || ORIG_REF_NAME==design_1_auto_us_90} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_91/design_1_auto_us_91.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_91 || ORIG_REF_NAME==design_1_auto_us_91} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_92/design_1_auto_us_92.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_92 || ORIG_REF_NAME==design_1_auto_us_92} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_93/design_1_auto_us_93.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_93 || ORIG_REF_NAME==design_1_auto_us_93} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_94/design_1_auto_us_94.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_94 || ORIG_REF_NAME==design_1_auto_us_94} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_95/design_1_auto_us_95.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_95 || ORIG_REF_NAME==design_1_auto_us_95} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_14/design_1_axi_interconnect_0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_14 || ORIG_REF_NAME==design_1_axi_interconnect_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_9/design_1_smartconnect_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_9 || ORIG_REF_NAME==design_1_smartconnect_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_60/design_1_CAMC_0_60.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_60 || ORIG_REF_NAME==design_1_CAMC_0_60} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_60/design_1_axi_bram_ctrl_0_60.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_60 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_60} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_61/design_1_axi_dma_0_61.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_61 || ORIG_REF_NAME==design_1_axi_dma_0_61} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_59/design_1_axi_dma_1_59.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_59 || ORIG_REF_NAME==design_1_axi_dma_1_59} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_60/design_1_blk_mem_gen_0_60.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_60 || ORIG_REF_NAME==design_1_blk_mem_gen_0_60} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_61/design_1_CAMC_0_61.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_61 || ORIG_REF_NAME==design_1_CAMC_0_61} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_61/design_1_axi_bram_ctrl_0_61.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_61 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_61} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_62/design_1_axi_dma_0_62.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_62 || ORIG_REF_NAME==design_1_axi_dma_0_62} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_60/design_1_axi_dma_1_60.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_60 || ORIG_REF_NAME==design_1_axi_dma_1_60} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_61/design_1_blk_mem_gen_0_61.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_61 || ORIG_REF_NAME==design_1_blk_mem_gen_0_61} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_62/design_1_CAMC_0_62.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_62 || ORIG_REF_NAME==design_1_CAMC_0_62} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_62/design_1_axi_bram_ctrl_0_62.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_62 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_62} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_63/design_1_axi_dma_0_63.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_63 || ORIG_REF_NAME==design_1_axi_dma_0_63} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_61/design_1_axi_dma_1_61.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_61 || ORIG_REF_NAME==design_1_axi_dma_1_61} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_62/design_1_blk_mem_gen_0_62.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_62 || ORIG_REF_NAME==design_1_blk_mem_gen_0_62} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_63/design_1_CAMC_0_63.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_63 || ORIG_REF_NAME==design_1_CAMC_0_63} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_63/design_1_axi_bram_ctrl_0_63.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_63 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_63} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_64/design_1_axi_dma_0_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_64 || ORIG_REF_NAME==design_1_axi_dma_0_64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_62/design_1_axi_dma_1_62.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_62 || ORIG_REF_NAME==design_1_axi_dma_1_62} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_63/design_1_blk_mem_gen_0_63.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_63 || ORIG_REF_NAME==design_1_blk_mem_gen_0_63} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_15/design_1_xbar_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_15 || ORIG_REF_NAME==design_1_xbar_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_96/design_1_auto_us_96.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_96 || ORIG_REF_NAME==design_1_auto_us_96} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_97/design_1_auto_us_97.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_97 || ORIG_REF_NAME==design_1_auto_us_97} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_98/design_1_auto_us_98.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_98 || ORIG_REF_NAME==design_1_auto_us_98} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_99/design_1_auto_us_99.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_99 || ORIG_REF_NAME==design_1_auto_us_99} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_100/design_1_auto_us_100.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_100 || ORIG_REF_NAME==design_1_auto_us_100} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_101/design_1_auto_us_101.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_101 || ORIG_REF_NAME==design_1_auto_us_101} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_102/design_1_auto_us_102.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_102 || ORIG_REF_NAME==design_1_auto_us_102} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_103/design_1_auto_us_103.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_103 || ORIG_REF_NAME==design_1_auto_us_103} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_104/design_1_auto_us_104.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_104 || ORIG_REF_NAME==design_1_auto_us_104} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_105/design_1_auto_us_105.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_105 || ORIG_REF_NAME==design_1_auto_us_105} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_106/design_1_auto_us_106.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_106 || ORIG_REF_NAME==design_1_auto_us_106} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_107/design_1_auto_us_107.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_107 || ORIG_REF_NAME==design_1_auto_us_107} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_108/design_1_auto_us_108.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_108 || ORIG_REF_NAME==design_1_auto_us_108} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_109/design_1_auto_us_109.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_109 || ORIG_REF_NAME==design_1_auto_us_109} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_110/design_1_auto_us_110.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_110 || ORIG_REF_NAME==design_1_auto_us_110} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_111/design_1_auto_us_111.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_111 || ORIG_REF_NAME==design_1_auto_us_111} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_15/design_1_axi_interconnect_0_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_15 || ORIG_REF_NAME==design_1_axi_interconnect_0_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_10/design_1_smartconnect_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_10 || ORIG_REF_NAME==design_1_smartconnect_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_64/design_1_CAMC_0_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_64 || ORIG_REF_NAME==design_1_CAMC_0_64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_64/design_1_axi_bram_ctrl_0_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_64 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_65/design_1_axi_dma_0_65.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_65 || ORIG_REF_NAME==design_1_axi_dma_0_65} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_63/design_1_axi_dma_1_63.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_63 || ORIG_REF_NAME==design_1_axi_dma_1_63} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_64/design_1_blk_mem_gen_0_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_64 || ORIG_REF_NAME==design_1_blk_mem_gen_0_64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_65/design_1_CAMC_0_65.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_65 || ORIG_REF_NAME==design_1_CAMC_0_65} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_65/design_1_axi_bram_ctrl_0_65.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_65 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_65} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_66/design_1_axi_dma_0_66.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_66 || ORIG_REF_NAME==design_1_axi_dma_0_66} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_64/design_1_axi_dma_1_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_64 || ORIG_REF_NAME==design_1_axi_dma_1_64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_65/design_1_blk_mem_gen_0_65.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_65 || ORIG_REF_NAME==design_1_blk_mem_gen_0_65} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_66/design_1_CAMC_0_66.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_66 || ORIG_REF_NAME==design_1_CAMC_0_66} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_66/design_1_axi_bram_ctrl_0_66.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_66 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_66} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_67/design_1_axi_dma_0_67.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_67 || ORIG_REF_NAME==design_1_axi_dma_0_67} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_65/design_1_axi_dma_1_65.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_65 || ORIG_REF_NAME==design_1_axi_dma_1_65} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_66/design_1_blk_mem_gen_0_66.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_66 || ORIG_REF_NAME==design_1_blk_mem_gen_0_66} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_67/design_1_CAMC_0_67.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_67 || ORIG_REF_NAME==design_1_CAMC_0_67} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_67/design_1_axi_bram_ctrl_0_67.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_67 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_67} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_68/design_1_axi_dma_0_68.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_68 || ORIG_REF_NAME==design_1_axi_dma_0_68} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_66/design_1_axi_dma_1_66.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_66 || ORIG_REF_NAME==design_1_axi_dma_1_66} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_67/design_1_blk_mem_gen_0_67.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_67 || ORIG_REF_NAME==design_1_blk_mem_gen_0_67} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_16/design_1_xbar_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_16 || ORIG_REF_NAME==design_1_xbar_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_112/design_1_auto_us_112.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_112 || ORIG_REF_NAME==design_1_auto_us_112} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_113/design_1_auto_us_113.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_113 || ORIG_REF_NAME==design_1_auto_us_113} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_114/design_1_auto_us_114.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_114 || ORIG_REF_NAME==design_1_auto_us_114} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_115/design_1_auto_us_115.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_115 || ORIG_REF_NAME==design_1_auto_us_115} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_116/design_1_auto_us_116.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_116 || ORIG_REF_NAME==design_1_auto_us_116} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_117/design_1_auto_us_117.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_117 || ORIG_REF_NAME==design_1_auto_us_117} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_118/design_1_auto_us_118.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_118 || ORIG_REF_NAME==design_1_auto_us_118} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_119/design_1_auto_us_119.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_119 || ORIG_REF_NAME==design_1_auto_us_119} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_120/design_1_auto_us_120.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_120 || ORIG_REF_NAME==design_1_auto_us_120} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_121/design_1_auto_us_121.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_121 || ORIG_REF_NAME==design_1_auto_us_121} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_122/design_1_auto_us_122.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_122 || ORIG_REF_NAME==design_1_auto_us_122} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_123/design_1_auto_us_123.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_123 || ORIG_REF_NAME==design_1_auto_us_123} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_124/design_1_auto_us_124.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_124 || ORIG_REF_NAME==design_1_auto_us_124} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_125/design_1_auto_us_125.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_125 || ORIG_REF_NAME==design_1_auto_us_125} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_126/design_1_auto_us_126.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_126 || ORIG_REF_NAME==design_1_auto_us_126} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_127/design_1_auto_us_127.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_127 || ORIG_REF_NAME==design_1_auto_us_127} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_16/design_1_axi_interconnect_0_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_16 || ORIG_REF_NAME==design_1_axi_interconnect_0_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_11/design_1_smartconnect_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_11 || ORIG_REF_NAME==design_1_smartconnect_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M_1 || ORIG_REF_NAME==design_1_rst_ps8_0_96M_1} -quiet] -quiet

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/design_1_ooc.xdc
