# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_0/design_1_CAMC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_0 || ORIG_REF_NAME==design_1_CAMC_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_1/design_1_CAMC_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_1 || ORIG_REF_NAME==design_1_CAMC_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_1 || ORIG_REF_NAME==design_1_axi_dma_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_2/design_1_axi_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_2 || ORIG_REF_NAME==design_1_axi_dma_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_0 || ORIG_REF_NAME==design_1_axi_dma_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_3/design_1_CAMC_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_3 || ORIG_REF_NAME==design_1_CAMC_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_3/design_1_axi_bram_ctrl_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_3 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_1_0/design_1_CAMC_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_1_0 || ORIG_REF_NAME==design_1_CAMC_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_4/design_1_axi_dma_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_4 || ORIG_REF_NAME==design_1_axi_dma_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_2/design_1_axi_dma_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_2 || ORIG_REF_NAME==design_1_axi_dma_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_2_0 || ORIG_REF_NAME==design_1_axi_dma_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_3_0/design_1_axi_dma_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_3_0 || ORIG_REF_NAME==design_1_axi_dma_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_3/design_1_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_3 || ORIG_REF_NAME==design_1_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_0 || ORIG_REF_NAME==design_1_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_1/design_1_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_1 || ORIG_REF_NAME==design_1_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_4/design_1_CAMC_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_4 || ORIG_REF_NAME==design_1_CAMC_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_4/design_1_axi_bram_ctrl_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_4 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_1_1/design_1_CAMC_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_1_1 || ORIG_REF_NAME==design_1_CAMC_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_1/design_1_axi_bram_ctrl_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_5/design_1_axi_dma_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_5 || ORIG_REF_NAME==design_1_axi_dma_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_3/design_1_axi_dma_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_3 || ORIG_REF_NAME==design_1_axi_dma_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_2_1/design_1_axi_dma_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_2_1 || ORIG_REF_NAME==design_1_axi_dma_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_3_1/design_1_axi_dma_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_3_1 || ORIG_REF_NAME==design_1_axi_dma_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_4/design_1_blk_mem_gen_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_4 || ORIG_REF_NAME==design_1_blk_mem_gen_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_1/design_1_blk_mem_gen_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_1 || ORIG_REF_NAME==design_1_blk_mem_gen_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_2/design_1_axi_interconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_2 || ORIG_REF_NAME==design_1_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_5/design_1_CAMC_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_5 || ORIG_REF_NAME==design_1_CAMC_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_5/design_1_axi_bram_ctrl_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_5 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_1_2/design_1_CAMC_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_1_2 || ORIG_REF_NAME==design_1_CAMC_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_2/design_1_axi_bram_ctrl_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_2 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_6/design_1_axi_dma_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_6 || ORIG_REF_NAME==design_1_axi_dma_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_4/design_1_axi_dma_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_4 || ORIG_REF_NAME==design_1_axi_dma_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_2_2/design_1_axi_dma_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_2_2 || ORIG_REF_NAME==design_1_axi_dma_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_3_2/design_1_axi_dma_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_3_2 || ORIG_REF_NAME==design_1_axi_dma_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_5/design_1_blk_mem_gen_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_5 || ORIG_REF_NAME==design_1_blk_mem_gen_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_2/design_1_blk_mem_gen_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_2 || ORIG_REF_NAME==design_1_blk_mem_gen_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_3/design_1_axi_interconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_3 || ORIG_REF_NAME==design_1_axi_interconnect_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_6/design_1_CAMC_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_6 || ORIG_REF_NAME==design_1_CAMC_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_6 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_1_3/design_1_CAMC_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_1_3 || ORIG_REF_NAME==design_1_CAMC_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_3/design_1_axi_bram_ctrl_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_3 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_7 || ORIG_REF_NAME==design_1_axi_dma_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_5/design_1_axi_dma_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_5 || ORIG_REF_NAME==design_1_axi_dma_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_2_3/design_1_axi_dma_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_2_3 || ORIG_REF_NAME==design_1_axi_dma_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_3_3/design_1_axi_dma_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_3_3 || ORIG_REF_NAME==design_1_axi_dma_3_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_6/design_1_blk_mem_gen_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_6 || ORIG_REF_NAME==design_1_blk_mem_gen_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_3/design_1_blk_mem_gen_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_3 || ORIG_REF_NAME==design_1_blk_mem_gen_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_4 || ORIG_REF_NAME==design_1_xbar_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_4/design_1_axi_interconnect_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_4 || ORIG_REF_NAME==design_1_axi_interconnect_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_7/design_1_CAMC_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_7 || ORIG_REF_NAME==design_1_CAMC_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_7/design_1_axi_bram_ctrl_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_7 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_1_4/design_1_CAMC_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_1_4 || ORIG_REF_NAME==design_1_CAMC_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_4/design_1_axi_bram_ctrl_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_4 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_8/design_1_axi_dma_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_8 || ORIG_REF_NAME==design_1_axi_dma_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_6/design_1_axi_dma_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_6 || ORIG_REF_NAME==design_1_axi_dma_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_2_4/design_1_axi_dma_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_2_4 || ORIG_REF_NAME==design_1_axi_dma_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_3_4/design_1_axi_dma_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_3_4 || ORIG_REF_NAME==design_1_axi_dma_3_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_7/design_1_blk_mem_gen_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_7 || ORIG_REF_NAME==design_1_blk_mem_gen_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_4/design_1_blk_mem_gen_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_4 || ORIG_REF_NAME==design_1_blk_mem_gen_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_5 || ORIG_REF_NAME==design_1_xbar_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_5/design_1_axi_interconnect_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_5 || ORIG_REF_NAME==design_1_axi_interconnect_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_4 || ORIG_REF_NAME==design_1_auto_us_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_5 || ORIG_REF_NAME==design_1_auto_us_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_6 || ORIG_REF_NAME==design_1_auto_us_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_7 || ORIG_REF_NAME==design_1_auto_us_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_8/design_1_auto_us_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_8 || ORIG_REF_NAME==design_1_auto_us_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_9/design_1_auto_us_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_9 || ORIG_REF_NAME==design_1_auto_us_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_10/design_1_auto_us_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_10 || ORIG_REF_NAME==design_1_auto_us_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_11/design_1_auto_us_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_11 || ORIG_REF_NAME==design_1_auto_us_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_12/design_1_auto_us_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_12 || ORIG_REF_NAME==design_1_auto_us_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_13/design_1_auto_us_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_13 || ORIG_REF_NAME==design_1_auto_us_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_14/design_1_auto_us_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_14 || ORIG_REF_NAME==design_1_auto_us_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_15/design_1_auto_us_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_15 || ORIG_REF_NAME==design_1_auto_us_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_16/design_1_auto_us_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_16 || ORIG_REF_NAME==design_1_auto_us_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_17/design_1_auto_us_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_17 || ORIG_REF_NAME==design_1_auto_us_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_18/design_1_auto_us_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_18 || ORIG_REF_NAME==design_1_auto_us_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_19/design_1_auto_us_19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_19 || ORIG_REF_NAME==design_1_auto_us_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_20/design_1_auto_us_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_20 || ORIG_REF_NAME==design_1_auto_us_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_21/design_1_auto_us_21.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_21 || ORIG_REF_NAME==design_1_auto_us_21} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_22/design_1_auto_us_22.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_22 || ORIG_REF_NAME==design_1_auto_us_22} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_23/design_1_auto_us_23.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_23 || ORIG_REF_NAME==design_1_auto_us_23} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_24/design_1_auto_us_24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_24 || ORIG_REF_NAME==design_1_auto_us_24} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_25/design_1_auto_us_25.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_25 || ORIG_REF_NAME==design_1_auto_us_25} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_26/design_1_auto_us_26.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_26 || ORIG_REF_NAME==design_1_auto_us_26} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_27/design_1_auto_us_27.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_27 || ORIG_REF_NAME==design_1_auto_us_27} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_28/design_1_auto_us_28.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_28 || ORIG_REF_NAME==design_1_auto_us_28} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_29/design_1_auto_us_29.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_29 || ORIG_REF_NAME==design_1_auto_us_29} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_30/design_1_auto_us_30.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_30 || ORIG_REF_NAME==design_1_auto_us_30} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_31/design_1_auto_us_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_31 || ORIG_REF_NAME==design_1_auto_us_31} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_32/design_1_auto_us_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_32 || ORIG_REF_NAME==design_1_auto_us_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_33/design_1_auto_us_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_33 || ORIG_REF_NAME==design_1_auto_us_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_34/design_1_auto_us_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_34 || ORIG_REF_NAME==design_1_auto_us_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_35/design_1_auto_us_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_35 || ORIG_REF_NAME==design_1_auto_us_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_36/design_1_auto_us_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_36 || ORIG_REF_NAME==design_1_auto_us_36} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_37/design_1_auto_us_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_37 || ORIG_REF_NAME==design_1_auto_us_37} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_38/design_1_auto_us_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_38 || ORIG_REF_NAME==design_1_auto_us_38} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_39/design_1_auto_us_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_39 || ORIG_REF_NAME==design_1_auto_us_39} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_40/design_1_auto_us_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_40 || ORIG_REF_NAME==design_1_auto_us_40} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_41/design_1_auto_us_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_41 || ORIG_REF_NAME==design_1_auto_us_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_42/design_1_auto_us_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_42 || ORIG_REF_NAME==design_1_auto_us_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_43/design_1_auto_us_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_43 || ORIG_REF_NAME==design_1_auto_us_43} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_44/design_1_auto_us_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_44 || ORIG_REF_NAME==design_1_auto_us_44} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_45/design_1_auto_us_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_45 || ORIG_REF_NAME==design_1_auto_us_45} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_46/design_1_auto_us_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_46 || ORIG_REF_NAME==design_1_auto_us_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_47/design_1_auto_us_47.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_47 || ORIG_REF_NAME==design_1_auto_us_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CAMC_0_8/design_1_CAMC_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CAMC_0_8 || ORIG_REF_NAME==design_1_CAMC_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_9/design_1_axi_dma_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_9 || ORIG_REF_NAME==design_1_axi_dma_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_7/design_1_axi_dma_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_7 || ORIG_REF_NAME==design_1_axi_dma_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_8/design_1_blk_mem_gen_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_8 || ORIG_REF_NAME==design_1_blk_mem_gen_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_6/design_1_xbar_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_6 || ORIG_REF_NAME==design_1_xbar_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_48/design_1_auto_us_48.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_48 || ORIG_REF_NAME==design_1_auto_us_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_49/design_1_auto_us_49.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_49 || ORIG_REF_NAME==design_1_auto_us_49} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_50/design_1_auto_us_50.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_50 || ORIG_REF_NAME==design_1_auto_us_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_51/design_1_auto_us_51.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_51 || ORIG_REF_NAME==design_1_auto_us_51} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_6/design_1_axi_interconnect_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_6 || ORIG_REF_NAME==design_1_axi_interconnect_0_6} -quiet] -quiet

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_32_30DMA_HPHPC/CAMC_24DMA_HPHPC.gen/sources_1/bd/design_1/design_1_ooc.xdc
