# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_24DMA_HPHPC/CAMC_24DMA_HPHPC.srcs/sources_1/bd/design_1/ip/design_1_CAMC_0_1/design_1_CAMC_0_1.xci
# IP: The module: 'design_1_CAMC_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_24DMA_HPHPC/CAMC_24DMA_HPHPC.gen/sources_1/bd/design_1/ip/design_1_CAMC_0_1/constraints/CAMC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_CAMC_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_24DMA_HPHPC/CAMC_24DMA_HPHPC.srcs/sources_1/bd/design_1/ip/design_1_CAMC_0_1/design_1_CAMC_0_1.xci
# IP: The module: 'design_1_CAMC_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_24DMA_HPHPC/CAMC_24DMA_HPHPC.gen/sources_1/bd/design_1/ip/design_1_CAMC_0_1/constraints/CAMC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_CAMC_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
