# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_35/design_1_axi_bram_ctrl_0_35.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_35' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_35/design_1_axi_bram_ctrl_0_35_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_35'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_35/design_1_axi_bram_ctrl_0_35.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_35' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/elx22yz/Desktop/RFSoC/Vivado/VivadoFile/CAMC_Full_128/CAMC_Full_128.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_35/design_1_axi_bram_ctrl_0_35_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_35'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
