// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CAMC_ArrayProduct (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weights_test_address0,
        weights_test_ce0,
        weights_test_q0,
        sum_BPSK,
        sum_BPSK_ap_vld,
        sum_BPSK_45m,
        sum_BPSK_45m_ap_vld,
        sum_BPSK_45p,
        sum_BPSK_45p_ap_vld,
        sum_BPSK_90p,
        sum_BPSK_90p_ap_vld,
        sum_QPSK,
        sum_QPSK_ap_vld,
        sum_QPSK_45m,
        sum_QPSK_45m_ap_vld,
        sum_8PSK,
        sum_8PSK_ap_vld,
        sum_8PSK_45m,
        sum_8PSK_45m_ap_vld,
        sum_16QAM,
        sum_16QAM_ap_vld,
        sum_16QAM_45m,
        sum_16QAM_45m_ap_vld
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] weights_test_address0;
output   weights_test_ce0;
input  [13:0] weights_test_q0;
output  [30:0] sum_BPSK;
output   sum_BPSK_ap_vld;
output  [30:0] sum_BPSK_45m;
output   sum_BPSK_45m_ap_vld;
output  [30:0] sum_BPSK_45p;
output   sum_BPSK_45p_ap_vld;
output  [30:0] sum_BPSK_90p;
output   sum_BPSK_90p_ap_vld;
output  [30:0] sum_QPSK;
output   sum_QPSK_ap_vld;
output  [30:0] sum_QPSK_45m;
output   sum_QPSK_45m_ap_vld;
output  [30:0] sum_8PSK;
output   sum_8PSK_ap_vld;
output  [30:0] sum_8PSK_45m;
output   sum_8PSK_45m_ap_vld;
output  [31:0] sum_16QAM;
output   sum_16QAM_ap_vld;
output  [31:0] sum_16QAM_45m;
output   sum_16QAM_45m_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] weights_test_address0;
reg weights_test_ce0;
reg sum_BPSK_ap_vld;
reg sum_BPSK_45m_ap_vld;
reg sum_BPSK_45p_ap_vld;
reg sum_BPSK_90p_ap_vld;
reg sum_QPSK_ap_vld;
reg sum_QPSK_45m_ap_vld;
reg sum_8PSK_ap_vld;
reg sum_8PSK_45m_ap_vld;
reg sum_16QAM_ap_vld;
reg sum_16QAM_45m_ap_vld;

(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_ready;
wire   [30:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_ready;
wire   [31:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_weights_test_ce0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_done;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_idle;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_ready;
wire   [31:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_p_out;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_p_out_ap_vld;
wire   [13:0] grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_weights_test_address0;
wire    grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_weights_test_ce0;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg   [20:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 21'd1;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start_reg = 1'b0;
#0 grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start_reg = 1'b0;
end

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_181_1 grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_187_2 grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_193_3 grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_200_4 grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_211_5 grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_216_6 grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_231_7 grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_235_8 grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_250_9 grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_256_10 grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start),
    .ap_done(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_done),
    .ap_idle(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_idle),
    .ap_ready(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_ready),
    .p_out(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_p_out),
    .p_out_ap_vld(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_p_out_ap_vld),
    .weights_test_address0(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_weights_test_address0),
    .weights_test_ce0(grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_weights_test_ce0),
    .weights_test_q0(weights_test_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start_reg <= 1'b1;
        end else if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_ready == 1'b1)) begin
            grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_16QAM_45m_ap_vld = 1'b1;
    end else begin
        sum_16QAM_45m_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_16QAM_ap_vld = 1'b1;
    end else begin
        sum_16QAM_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_8PSK_45m_ap_vld = 1'b1;
    end else begin
        sum_8PSK_45m_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_8PSK_ap_vld = 1'b1;
    end else begin
        sum_8PSK_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_BPSK_45m_ap_vld = 1'b1;
    end else begin
        sum_BPSK_45m_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_BPSK_45p_ap_vld = 1'b1;
    end else begin
        sum_BPSK_45p_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_BPSK_90p_ap_vld = 1'b1;
    end else begin
        sum_BPSK_90p_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_BPSK_ap_vld = 1'b1;
    end else begin
        sum_BPSK_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_QPSK_45m_ap_vld = 1'b1;
    end else begin
        sum_QPSK_45m_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sum_QPSK_ap_vld = 1'b1;
    end else begin
        sum_QPSK_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_weights_test_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        weights_test_address0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_weights_test_address0;
    end else begin
        weights_test_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_weights_test_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        weights_test_ce0 = grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_weights_test_ce0;
    end else begin
        weights_test_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_ap_start_reg;

assign grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start = grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_ap_start_reg;

assign sum_16QAM = grp_ArrayProduct_Pipeline_VITIS_LOOP_250_9_fu_248_p_out;

assign sum_16QAM_45m = grp_ArrayProduct_Pipeline_VITIS_LOOP_256_10_fu_261_p_out;

assign sum_8PSK = grp_ArrayProduct_Pipeline_VITIS_LOOP_231_7_fu_222_p_out;

assign sum_8PSK_45m = grp_ArrayProduct_Pipeline_VITIS_LOOP_235_8_fu_235_p_out;

assign sum_BPSK = grp_ArrayProduct_Pipeline_VITIS_LOOP_181_1_fu_144_p_out;

assign sum_BPSK_45m = grp_ArrayProduct_Pipeline_VITIS_LOOP_187_2_fu_157_p_out;

assign sum_BPSK_45p = grp_ArrayProduct_Pipeline_VITIS_LOOP_193_3_fu_170_p_out;

assign sum_BPSK_90p = grp_ArrayProduct_Pipeline_VITIS_LOOP_200_4_fu_183_p_out;

assign sum_QPSK = grp_ArrayProduct_Pipeline_VITIS_LOOP_211_5_fu_196_p_out;

assign sum_QPSK_45m = grp_ArrayProduct_Pipeline_VITIS_LOOP_216_6_fu_209_p_out;

endmodule //CAMC_ArrayProduct
