// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CAMC_ArrayProduct_Pipeline_VITIS_LOOP_250_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_out,
        p_out_ap_vld,
        weights_test_address0,
        weights_test_ce0,
        weights_test_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [13:0] weights_test_address0;
output   weights_test_ce0;
input  [13:0] weights_test_q0;

reg ap_idle;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln250_fu_124_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] Lite_16QAM_weight_X_10_address0;
wire   [6:0] Lite_16QAM_weight_X_10_q0;
wire   [8:0] Lite_16QAM_weight_Y_10_address0;
wire   [6:0] Lite_16QAM_weight_Y_10_q0;
wire   [8:0] Lite_16QAM_weight_10_address0;
wire   [8:0] Lite_16QAM_weight_10_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln250_reg_226;
reg   [0:0] icmp_ln250_reg_226_pp0_iter1_reg;
reg   [0:0] icmp_ln250_reg_226_pp0_iter2_reg;
reg   [0:0] icmp_ln250_reg_226_pp0_iter3_reg;
reg   [0:0] icmp_ln250_reg_226_pp0_iter4_reg;
reg   [0:0] icmp_ln250_reg_226_pp0_iter5_reg;
reg   [0:0] icmp_ln250_reg_226_pp0_iter6_reg;
reg   [6:0] Lite_16QAM_weight_Y_10_load_reg_250;
reg   [6:0] Lite_16QAM_weight_Y_10_load_reg_250_pp0_iter2_reg;
reg   [8:0] Lite_16QAM_weight_10_load_reg_255;
reg   [8:0] Lite_16QAM_weight_10_load_reg_255_pp0_iter2_reg;
reg   [8:0] Lite_16QAM_weight_10_load_reg_255_pp0_iter3_reg;
reg   [8:0] Lite_16QAM_weight_10_load_reg_255_pp0_iter4_reg;
wire   [63:0] zext_ln250_fu_136_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln253_4_fu_170_p1;
reg   [31:0] empty_fu_44;
wire   [31:0] grp_fu_202_p3;
reg   [31:0] ap_sig_allocacmp_p_load;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [8:0] i_fu_48;
wire   [8:0] add_ln250_fu_130_p2;
reg   [8:0] ap_sig_allocacmp_i_4;
wire    ap_block_pp0_stage0_01001;
reg    Lite_16QAM_weight_X_10_ce0_local;
reg    Lite_16QAM_weight_Y_10_ce0_local;
reg    Lite_16QAM_weight_10_ce0_local;
reg    weights_test_ce0_local;
wire   [7:0] zext_ln253_fu_148_p1;
wire  signed [7:0] add_ln253_fu_152_p2;
wire  signed [13:0] add_ln253_2_fu_165_p0;
wire   [13:0] grp_fu_193_p3;
(* use_dsp48 = "no" *) wire   [13:0] add_ln253_2_fu_165_p2;
wire   [6:0] grp_fu_193_p1;
wire   [6:0] grp_fu_193_p2;
wire   [13:0] grp_fu_202_p0;
wire   [8:0] grp_fu_202_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [13:0] grp_fu_193_p20;
wire   [22:0] grp_fu_202_p00;
wire   [22:0] grp_fu_202_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 empty_fu_44 = 32'd0;
#0 i_fu_48 = 9'd0;
#0 ap_done_reg = 1'b0;
end

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_250_9_Lite_16QAM_weight_X_10_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 358 ),
    .AddressWidth( 9 ))
Lite_16QAM_weight_X_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Lite_16QAM_weight_X_10_address0),
    .ce0(Lite_16QAM_weight_X_10_ce0_local),
    .q0(Lite_16QAM_weight_X_10_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_250_9_Lite_16QAM_weight_Y_10_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 358 ),
    .AddressWidth( 9 ))
Lite_16QAM_weight_Y_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Lite_16QAM_weight_Y_10_address0),
    .ce0(Lite_16QAM_weight_Y_10_ce0_local),
    .q0(Lite_16QAM_weight_Y_10_q0)
);

CAMC_ArrayProduct_Pipeline_VITIS_LOOP_250_9_Lite_16QAM_weight_10_ROM_AUTO_1R #(
    .DataWidth( 9 ),
    .AddressRange( 358 ),
    .AddressWidth( 9 ))
Lite_16QAM_weight_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Lite_16QAM_weight_10_address0),
    .ce0(Lite_16QAM_weight_10_ce0_local),
    .q0(Lite_16QAM_weight_10_q0)
);

CAMC_mac_muladd_8s_7ns_7ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mac_muladd_8s_7ns_7ns_14_4_1_U108(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln253_fu_152_p2),
    .din1(grp_fu_193_p1),
    .din2(grp_fu_193_p2),
    .ce(1'b1),
    .dout(grp_fu_193_p3)
);

CAMC_mac_muladd_14ns_9ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_14ns_9ns_32ns_32_4_1_U109(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_202_p0),
    .din1(grp_fu_202_p1),
    .din2(ap_sig_allocacmp_p_load),
    .ce(1'b1),
    .dout(grp_fu_202_p3)
);

CAMC_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_fu_44 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            empty_fu_44 <= grp_fu_202_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln250_fu_124_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_48 <= add_ln250_fu_130_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lite_16QAM_weight_10_load_reg_255 <= Lite_16QAM_weight_10_q0;
        Lite_16QAM_weight_Y_10_load_reg_250 <= Lite_16QAM_weight_Y_10_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln250_reg_226 <= icmp_ln250_fu_124_p2;
        icmp_ln250_reg_226_pp0_iter1_reg <= icmp_ln250_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Lite_16QAM_weight_10_load_reg_255_pp0_iter2_reg <= Lite_16QAM_weight_10_load_reg_255;
        Lite_16QAM_weight_10_load_reg_255_pp0_iter3_reg <= Lite_16QAM_weight_10_load_reg_255_pp0_iter2_reg;
        Lite_16QAM_weight_10_load_reg_255_pp0_iter4_reg <= Lite_16QAM_weight_10_load_reg_255_pp0_iter3_reg;
        Lite_16QAM_weight_Y_10_load_reg_250_pp0_iter2_reg <= Lite_16QAM_weight_Y_10_load_reg_250;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln250_reg_226_pp0_iter2_reg <= icmp_ln250_reg_226_pp0_iter1_reg;
        icmp_ln250_reg_226_pp0_iter3_reg <= icmp_ln250_reg_226_pp0_iter2_reg;
        icmp_ln250_reg_226_pp0_iter4_reg <= icmp_ln250_reg_226_pp0_iter3_reg;
        icmp_ln250_reg_226_pp0_iter5_reg <= icmp_ln250_reg_226_pp0_iter4_reg;
        icmp_ln250_reg_226_pp0_iter6_reg <= icmp_ln250_reg_226_pp0_iter5_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lite_16QAM_weight_10_ce0_local = 1'b1;
    end else begin
        Lite_16QAM_weight_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lite_16QAM_weight_X_10_ce0_local = 1'b1;
    end else begin
        Lite_16QAM_weight_X_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lite_16QAM_weight_Y_10_ce0_local = 1'b1;
    end else begin
        Lite_16QAM_weight_Y_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln250_fu_124_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_sig_allocacmp_p_load = grp_fu_202_p3;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (icmp_ln250_reg_226_pp0_iter6_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        weights_test_ce0_local = 1'b1;
    end else begin
        weights_test_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Lite_16QAM_weight_10_address0 = zext_ln250_fu_136_p1;

assign Lite_16QAM_weight_X_10_address0 = zext_ln250_fu_136_p1;

assign Lite_16QAM_weight_Y_10_address0 = zext_ln250_fu_136_p1;

assign add_ln250_fu_130_p2 = (ap_sig_allocacmp_i_4 + 9'd1);

assign add_ln253_2_fu_165_p0 = grp_fu_193_p3;

assign add_ln253_2_fu_165_p2 = ($signed(add_ln253_2_fu_165_p0) + $signed(14'd16383));

assign add_ln253_fu_152_p2 = ($signed(zext_ln253_fu_148_p1) + $signed(8'd255));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_193_p1 = 14'd100;

assign grp_fu_193_p2 = grp_fu_193_p20;

assign grp_fu_193_p20 = Lite_16QAM_weight_Y_10_load_reg_250_pp0_iter2_reg;

assign grp_fu_202_p0 = grp_fu_202_p00;

assign grp_fu_202_p00 = weights_test_q0;

assign grp_fu_202_p1 = grp_fu_202_p10;

assign grp_fu_202_p10 = Lite_16QAM_weight_10_load_reg_255_pp0_iter4_reg;

assign icmp_ln250_fu_124_p2 = ((ap_sig_allocacmp_i_4 == 9'd358) ? 1'b1 : 1'b0);

assign p_out = empty_fu_44;

assign weights_test_address0 = zext_ln253_4_fu_170_p1;

assign weights_test_ce0 = weights_test_ce0_local;

assign zext_ln250_fu_136_p1 = ap_sig_allocacmp_i_4;

assign zext_ln253_4_fu_170_p1 = add_ln253_2_fu_165_p2;

assign zext_ln253_fu_148_p1 = Lite_16QAM_weight_X_10_q0;

endmodule //CAMC_ArrayProduct_Pipeline_VITIS_LOOP_250_9
